#!/bin/bash

# Connect to the Snowflake account using the Access Token
snowsql \
    -a $SNOWFLAKE_ACCOUNT \
    -u $(terraform output -raw oauth_client_principal_id) \
    -r SNOWSQL_RL \
    --authenticator oauth \
    --token "$(./get-access-token)"