name: Run Azure CLI Login with OpenID Connect
on: [workflow_dispatch]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.AZURE_PRINCIPAL_ID }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_AUTHENTICATOR: OAUTH
      SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: SNOWSQL_RL
    
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true
  
    - name: Get Snowflake access token
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          access_token=$(az account get-access-token --scope ${{ secrets.OAUTH_SERVER_IDENTIFIER_URI }}/.default --query accessToken -o tsv)
          echo "SNOWFLAKE_CONNECTIONS_DEFAULT_TOKEN=$access_token" >> "$GITHUB_ENV"

    - name: Install Snowflake CLI
      uses: Snowflake-Labs/snowflake-cli-action@v1
      with:
        cli-version: latest
        default-config-file-path: config.toml

    - name: Execute Snowflake CLI command
      run: |
        snow --version
        snow connection test